### ISSUE TITLE
註冊畫面美化

### ISSUE THREAD

**Issue by Jimmy-Chen-2B** [5xDisco/Stork#47]
輸入框、按鈕要對齊
Apple 登入可以不用

![Screen Shot 2021-09-16 at 11 34 25](https://user-images.githubusercontent.com/15827441/133545256-7a1f58ad-b4e7-430c-a7fc-5070a0a8d439.png)

可參考排版

![Screen Shot 2021-09-16 at 11 41 37](https://user-images.githubusercontent.com/15827441/133545751-8f1c2af2-a5ae-4794-9b86-a14a4863e5a9.png)

**Comment by linchiquei** [comment]
下面才對
