### ISSUE TITLE
建立工作空間第二步，建立團隊的前端驗證JS

### ISSUE THREAD

**Issue by Jimmy-Chen-2B** [5xDisco/Stork#51]
![1631693011913](https://user-images.githubusercontent.com/86403735/133395009-ff439258-4190-4dda-92bf-1d123c02bb71.jpg)

**Comment by An-Chi** [comment]
預設預設會自動帶入 「新的工作空間」所以左邊 sidebar 才會出現新的工作空間字樣
step1 - 限制字數50字 , step2 限制字數80字，沒有輸入不能按下按鈕。
![Screen Shot 2021-09-22 at 14 10 23](https://user-images.githubusercontent.com/15827441/134291887-43b5dc24-17e5-4ca2-98ed-be1ebd3d9807.png)

![Screen Shot 2021-09-22 at 14 09 40](https://user-images.githubusercontent.com/15827441/134291773-fe8e8f97-73a3-40e2-aa2b-39d7e571d09a.png)
