### ISSUE TITLE
頻道列表的順序會跑掉 #bug

### ISSUE THREAD

**Issue by Jimmy-Chen-2B** [5xDisco/Stork#92]
創立一個頻道後，新頻道會在上方
但重新收闔之後，順序會跑掉

![unknown](https://user-images.githubusercontent.com/86403735/134464013-a1a60ed4-1e98-4e41-abac-982c72ca1c0a.png)
![image](https://user-images.githubusercontent.com/86403735/134464100-303f14dc-e202-4a4f-a05f-8002e4e24504.png)

**Comment by linchiquei** [comment]
@An-Chi 收合感覺不是每次都有作用！
@Jimmy-Chen-2B 這邊我在你跟我的 controller 上面也加上排序
`
    all_channels = current_user.channels.where(space_id: space.id, direct_message: false).order("ID ASC")
`
